---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: daemon-reload

- name: Restart the machine
  ansible.builtin.reboot:
    reboot_timeout: 3600
  listen: reboot
  when: "{{ ansible_hostname not == 'localhost' }}"
