--- 
- name: Install wazuh-agent
  ansible.builtin.package:
    name: wazuh-agent
    state: present

- name: Add manager ip
  ansible.builtin.lineinfile:
    path: /var/ossec/etc/ossec.conf
    regexp: "^\\s{6}<address>.*</address>"
    line: "      <address>135.181.124.121</address>"
  notify: restart service

- name: read config
  ansible.builtin.command: cat /var/ossec/etc/ossec.conf
  register: conf

- debug:
    msg: "{{conf}}"
